name: Deploy to Aliyun

on:
  push:
    branches: [v4]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull content and rebuild
        run: |
          cd ~/Obsidian && git pull
          cd ~/quartz && git pull && npx quartz build
